source 'https://rubygems.org'

gem 'rails', '~> 8.0.2'
gem 'sqlite3'
gem 'puma', '~> 6.0'
gem 'nokogiri'
gem 'httparty'
gem 'sidekiq'
gem 'dotenv-rails'

group :development, :test do
  gem 'pry'
  gem 'rspec-rails'
end
